# Generated by Django 2.0.5 on 2018-06-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0002_auto_20180604_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dweeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='dwitter.Dweeter')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whom', to='dwitter.Dweeter')),
            ],
        ),
        migrations.RemoveField(
            model_name='followers',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.AddField(
            model_name='dweeter',
            name='user',
            field=models.ManyToManyField(through='dwitter.Relationship', to='dwitter.Dweeter'),
        ),
    ]
