# Generated by Django 2.0.5 on 2018-06-05 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_auto_20180605_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dweeter',
            name='user',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked_on',
            new_name='dweet',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='messagebox',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='messagebox',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='messagebox',
            old_name='User_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dweeter',
        ),
    ]
